# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout AutoPlug-Client
      uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14

    - name: Create jar with Maven
      run: mvn -B clean package --file pom.xml
      
    - name: Copy jar to beta dir
      run: mkdir beta && cp target/AutoPlug.jar beta
      
    - name: Add update
      run: |
        git config --local user.email "osiris_support@pm.me"
        git config --local user.name "GitHub Action"
        git add beta/AutoPlug.jar
      
    - name: Confirm update
      run: |
        git config --local user.email "osiris_support@pm.me"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
      
    - name: Push/Upload update
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
      #We also want to have the jar at our Releases repo
    - name: Checkout AutoPlug-Releases
      uses: actions/checkout@master
      with:
        repository: 'Osiris-Team/AutoPlug-Releases'
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
      #Downloads the jar we uploaded 1sec ago to the AutoPlug-Client repo
    - name: Download jar
      run: mkdir beta && wget  -O /beta/AutoPlug.jar "https://github.com/Osiris-Team/AutoPlug-Client/raw/master/beta/AutoPlug.jar"
      
    - name: Add update
      run: |
        git config --local user.email "osiris_support@pm.me"
        git config --local user.name "GitHub Action"
        git add beta/AutoPlug.jar
      
    - name: Confirm update
      run: |
        git config --local user.email "osiris_support@pm.me"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
      
    - name: Push/Upload update
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

