# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout AutoPlug-Client
      uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      
    - name: Checkout AutoPlug-Releases
      uses: actions/checkout@master
      with:
        repository: 'Osiris-Team/AutoPlug-Releases'
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
    - name: Copy build to upload dir
      run: mkdir beta && cp target/AutoPlug.jar beta
      
    - name: Add AutoPlug.jar
      run: |
        git config --local user.email "osiris_support@pm.me"
        git config --local user.name "GitHub Action"
        git add beta/AutoPlug.jar

    - name: Commit all changes
      run: |
        git config --local user.email "osiris_support@pm.me"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: Osiris-Team/AutoPlug-Releases
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}

